name: flaskwebview
dependencies:
  - python=3.6
  - pandas
  - pip:
    - Flask
    - pywebview
    - CoolProp
    - flask-jwt-extended
    - flask-seasurf
    - flask-sqlalchemy
    - requests
    - pybtex
